### ISSUE TITLE
[error] Multiple repositories are found

### ISSUE THREAD

**Issue by gvolpe** [xerial/sbt-sonatype#142]
Did something change in recent versions that might have introduced a bug when cross-publishing?

These are the steps I've always followed:

```scala
$ +publishSigned
$ sonatypeRelease
```

This has always worked but now I keep on getting the following error in the release step:

```scala
[error] Multiple repositories are found:
[error] [devprofunktor-1048] status:open, profile:dev.profunktor(b2af0dabe72b1b) description: Implicitly created (auto staging).
[error] [devprofunktor-1049] status:open, profile:dev.profunktor(b2af0dabe72b1b) description: Implicitly created (auto staging).
[error] [devprofunktor-1050] status:open, profile:dev.profunktor(b2af0dabe72b1b) description: Implicitly created (auto staging).
[error] Specify one of the repository ids in the command line or run sonatypeDropAll to cleanup repositories
[error] java.lang.IllegalStateException: Found multiple staging repositories
[error] Use 'last' for the full log.
```

FWIW I tried dropping existing repositories many times using `sonatypeDropAll` but I still get the same error.

I'd appreciate any hints. Thanks.

**Comment by xerial** [comment]
@gvolpe Actually, the behavior has been changed in the sbt side, which suddenly creates too many implicit repositories at Sonatype. I still don't know the true cause. 

As a workaround, sbt-sonatype revised the entire release procedure so that we need only a single staging repository to publish multiple artifacts at once. See this article to see what has been changed: 
https://medium.com/@taroleo/sbt-sonatype-f02bdafd78f1

The latest version of sbt-sonatype will also perform some cleanup of previously failed staging repositories.

**Comment by gvolpe** [comment]
Hi @xerial , sorry for not coming back to you before.

I just had the chance to make a new release of one of the libraries I maintain and this issue seems to be fixed, using the latest versions of the plugins, which are updated by Scala Steward. Closing this.
