### ISSUE TITLE
add support to delete an already release.

### ISSUE THREAD

**Issue by hepin1989** [xerial/sbt-sonatype#20]

**Comment by xerial** [comment]
@hepin1989 
I don't think this is possible even if you use Sonatype's web console. If you need to remove staging repositories, use `sonatypeDrop (repository id)` command.

**Comment by hepin1989** [comment]
@xerial thanks,If you think this is invalid ,feel free to close it.
seems like the nexus could do that。thanks again.

**Comment by xerial** [comment]
@hepin1989 
From the list of REST API https://repository.sonatype.org/nexus-restlet1x-plugin/default/docs/index.html, I couldn't find any endpoint for deleting the already released artifacts. And I think we should not delete already released projects since it causes synchronization issues. 

Let me close this issue. Thanks.
