### ISSUE TITLE
Problem releasing multiple libraries in parallel

### ISSUE THREAD

**Issue by rtfpessoa** [xerial/sbt-sonatype#75]
Sometimes I have problems because two libraries are publishing at the same time and it fails due to repositories existing for the same profile.

How can I run `sonatypeRelease` for only the repository I just run `publishSigned`?

**Comment by xerial** [comment]
Here is some example to specify different profile names so that you can publish multiple libraries:
https://github.com/xerial/sbt-sonatype/blob/master/workflow.md

Disclaimer: Personally I'm not publishing multiple libraries into different locations (e.g., different organization paths), so I'm not sure whether it works for you.

**Comment by rtfpessoa** [comment]
@xerial I kind of fixed that problem for now and that might be the correct solution. Still I think my issue was to do cross release in different sbt sessions.
