### ISSUE TITLE
Cross publish v2.5 for sbt 0.13

### ISSUE THREAD

**Issue by albuch** [xerial/sbt-sonatype#85]
As far as I can tell cross publishing for SBT 0.13 got dropped starting with v2.4 of sbt-sonatype (https://repo1.maven.org/maven2/org/xerial/sbt/). Plugin developers who still want to support sbt 0.13 can't upgrade to the never versions of sbt-sonatype.
Is there a reason why the plugin is not cross-published to sbt 0.13 anymore?

**Comment by xerial** [comment]
sbt 0.13 is based on a quite old Scala 2.10 and I've been working hard to deprecate Scala 2.10 code assets, including sbt-sonatype. This is simply because supporting Scala 2.10 had been killing my time (including CI wait time, investigating test failures, finding compatible ways to support both sbt 1.x and 0.13, etc.) I have no time luxury to support sbt 0.13 anymore.

We are already in an era of sbt-1.x with Scala 2.12 for more than one year. I'd appreciate if you understand my effort for keep maintaining OSS projects.

**Comment by albuch** [comment]
Thanks @xerial, totally understand, especially if you're maintaining more than one plugin.
